### ISSUE TITLE
Use TrTextIdConverter in ControlTemplate not working

### ISSUE THREAD

**Issue by linhmc** [codingseb/Localization#1]
Dear Coding Seb,
Thank for useful project.
I have an issue please help. Language not change when select change in language combobox
```xml
<ControlTemplate TargetType="ListBoxItem">
    <Grid>
        <Grid x:Name="GridLevel0">
            <TextBlock Text="{Binding ContentName, Converter={TrTextIdConverter DefaultText='DefaultText'}, UpdateSourceTrigger=PropertyChanged}"/>
        </Grid>
    </Grid>
</ControlTemplate>
```

![image](https://user-images.githubusercontent.com/20184892/100694874-8e5c0780-33c2-11eb-9b29-02ca668e4d82.png)

**Comment by codingseb** [comment]
Hello @linhmc .
Where did you put your ControlTemplate ? I tried in a `ListBox.Resources' but VisualStudio do not like it without a Key and with a key it can not be applied.

Personally, I usually prefer to define a `DataTemplate` in `ListBox.ItemTemplate` or a `DataTemplateSelector` in `ListBox.ItemTemplateSelector` to customize the way ListBoxItems are shown.

__Something like that :__

```xml
<ListBox ItemsSource="{Binding Items}">
    <ListBox.ItemTemplate>
        <DataTemplate DataType="ListBoxItem">
            <Grid>
                <Grid x:Name="GridLevel0">
                    <TextBlock Text="{Binding ContentName, Converter={TrTextIdConverter DefaultText='DefaultText'}, UpdateSourceTrigger=PropertyChanged}"/>
                </Grid>
            </Grid>
        </DataTemplate>
    </ListBox.ItemTemplate>
</ListBox>
```

```c#
public class ItemViewModel
{
    public string ContentName { get; set; }
    public int OtherValue { get; set; }
}
```

```c#
public class MainViewModel
{
    // ...
    
    public ObservableCollection<ItemViewModel> Items { get; set; } = new ObservableCollection<ItemViewModel>()
    {
        new ItemViewModel()
        {
            ContentName="TextId1",
            OtherValue = 1
        },
        new ItemViewModel()
        {
            ContentName="TextId2",
            OtherValue=2
        }
    };
    
    // ...
}
```

This kind of stuff work for me.

**Comment by codingseb** [comment]
In fact, in templates, converters are not sensitive to language change. This is due to the way bindings works in templates.
This is why I addded the possibility to specify TextId as a Binding in Tr Markup in last version of `CodingSeb.Localization.WPF`.

__So you can do this :__
```xml
<ListBox ItemsSource="{Binding Items}">
    <ListBox.ItemTemplate>
        <DataTemplate DataType="ItemViewModel">
            <Grid>
                <Grid x:Name="GridLevel0">
                    <TextBlock Text="{Tr {Binding ContentName}, DefaultText='DefaultText'}"/>
                </Grid>
            </Grid>
        </DataTemplate>
    </ListBox.ItemTemplate>
</ListBox>
```

```xml
<DataTemplate DataType="ListBoxItem">
<!-- or  -->
<DataTemplate DataType="ItemViewModel">
<!-- Both work for me (Depending if you prefer to Template the UI ListBoxItem or the corresponding ViewModel type) -->
```

**Comment by linhmc** [comment]
> Hello @linhmc .
> Where did you put your ControlTemplate ? I tried in a `ListBox.Resources' but VisualStudio do not like it without a Key and with a key it can not be applied.
> 
> Personally, I usually prefer to define a `DataTemplate` in `ListBox.ItemTemplate` or a `DataTemplateSelector` in `ListBox.ItemTemplateSelector` to customize the way ListBoxItems are shown.
> 
> **Something like that :**
> 
> ```
> <ListBox ItemsSource="{Binding Items}">
>     <ListBox.ItemTemplate>
>         <DataTemplate DataType="ListBoxItem">
>             <Grid>
>                 <Grid x:Name="GridLevel0">
>                     <TextBlock Text="{Binding ContentName, Converter={TrTextIdConverter DefaultText='DefaultText'}, UpdateSourceTrigger=PropertyChanged}"/>
>                 </Grid>
>             </Grid>
>         </DataTemplate>
>     </ListBox.ItemTemplate>
> </ListBox>
> ```
> 
> ```cs
> public class ItemViewModel
> {
>     public string ContentName { get; set; }
>     public int OtherValue { get; set; }
> }
> ```
> 
> ```cs
> public class MainViewModel
> {
>     // ...
>     
>     public ObservableCollection<ItemViewModel> Items { get; set; } = new ObservableCollection<ItemViewModel>()
>     {
>         new ItemViewModel()
>         {
>             ContentName="TextId1",
>             OtherValue = 1
>         },
>         new ItemViewModel()
>         {
>             ContentName="TextId2",
>             OtherValue=2
>         }
>     };
>     
>     // ...
> }
> ```
> 
> This kind of stuff work for me.

Hi @codingseb 
Thank you for reply.
I put code in <ListBox.Resources> like this:
![image](https://user-images.githubusercontent.com/20184892/100715491-db070900-33e9-11eb-88fe-23bce78aedc3.png)

I'll try it your way.
Thank you so much.

**Comment by linhmc** [comment]
Hi @codingseb ,
I am coding to help user can change language in real-time. That mean user change in .tm.json file and save in text editor, in UI when user refresh button it change language automatically
![image](https://user-images.githubusercontent.com/20184892/100715956-90d25780-33ea-11eb-85c4-efccfdc35b05.png)
How can I get it?

**Comment by linhmc** [comment]
> In fact, in templates, converters are not sensitive to language change. This is due to the way bindings works in templates.
> This is why I addded the possibility to specify TextId as a Binding in Tr Markup in last version of `CodingSeb.Localization.WPF`.
> 
> **So you can do this :**
> 
> ```
> <ListBox ItemsSource="{Binding Items}">
>     <ListBox.ItemTemplate>
>         <DataTemplate DataType="ItemViewModel">
>             <Grid>
>                 <Grid x:Name="GridLevel0">
>                     <TextBlock Text="{Tr {Binding ContentName}, DefaultText='DefaultText'}"/>
>                 </Grid>
>             </Grid>
>         </DataTemplate>
>     </ListBox.ItemTemplate>
> </ListBox>
> ```
> 
> ```
> <DataTemplate DataType="ListBoxItem">
> 
> <DataTemplate DataType="ItemViewModel">
> 
> ```

Actually I am using TranslateMe version, don't know if it helps

**Comment by codingseb** [comment]
> Actually I am using TranslateMe version, don't know if it helps

OK, No it's not supported in TranslateMe I am sorry. Take note that TranslateMe archived and is now obsolete. It will not get further updates.
The CodingSeb.Localization suite is the new way to go. Normally, the change of library should only take a few changes.

**Comment by linhmc** [comment]
> > Hello @linhmc .
> > Where did you put your ControlTemplate ? I tried in a `ListBox.Resources' but VisualStudio do not like it without a Key and with a key it can not be applied.
> > Personally, I usually prefer to define a `DataTemplate` in `ListBox.ItemTemplate` or a `DataTemplateSelector` in `ListBox.ItemTemplateSelector` to customize the way ListBoxItems are shown.
> > **Something like that :**
> > ```
> > <ListBox ItemsSource="{Binding Items}">
> >     <ListBox.ItemTemplate>
> >         <DataTemplate DataType="ListBoxItem">
> >             <Grid>
> >                 <Grid x:Name="GridLevel0">
> >                     <TextBlock Text="{Binding ContentName, Converter={TrTextIdConverter DefaultText='DefaultText'}, UpdateSourceTrigger=PropertyChanged}"/>
> >                 </Grid>
> >             </Grid>
> >         </DataTemplate>
> >     </ListBox.ItemTemplate>
> > </ListBox>
> > ```
> > 
> > 
> > ```cs
> > public class ItemViewModel
> > {
> >     public string ContentName { get; set; }
> >     public int OtherValue { get; set; }
> > }
> > ```
> > 
> > 
> > ```cs
> > public class MainViewModel
> > {
> >     // ...
> >     
> >     public ObservableCollection<ItemViewModel> Items { get; set; } = new ObservableCollection<ItemViewModel>()
> >     {
> >         new ItemViewModel()
> >         {
> >             ContentName="TextId1",
> >             OtherValue = 1
> >         },
> >         new ItemViewModel()
> >         {
> >             ContentName="TextId2",
> >             OtherValue=2
> >         }
> >     };
> >     
> >     // ...
> > }
> > ```
> > 
> > 
> > This kind of stuff work for me.
> 
> Hi @codingseb
> Thank you for reply.
> I put code in <ListBox.Resources> like this:
> ![image](https://user-images.githubusercontent.com/20184892/100715491-db070900-33e9-11eb-88fe-23bce78aedc3.png)
> 
> I'll try it your way.
> Thank you so much.


Hi @codingseb 
I tried your suggest:
![image](https://user-images.githubusercontent.com/20184892/100719863-c594dd80-33ef-11eb-906c-7e0380dd0067.png)
but It is not work. Language not change when I selection changed other language.
![image](https://user-images.githubusercontent.com/20184892/100720118-1e647600-33f0-11eb-84c1-4ebec94b691b.png)

**Comment by codingseb** [comment]
> Hi @codingseb
> I tried your suggest:
> ![image](https://user-images.githubusercontent.com/20184892/100719863-c594dd80-33ef-11eb-906c-7e0380dd0067.png)
> but It is not work. Language not change when I selection changed other language.
> ![image](https://user-images.githubusercontent.com/20184892/100720118-1e647600-33f0-11eb-84c1-4ebec94b691b.png)

Yes because converters can not update a binding in a template. Because of the way WPF works with templates the converter can not get the `DependencyObject` and the `DependencyProperty` on which the binding is set and so can not update the value when language change in the case of a template. So the only way to make language change effective in a template is with the `Tr' Markup with TextId as Binding of `Localization.WPF` that create internally a MultiBinding.
```xml
<TextBlock Text="{Tr {Binding ContentName}, DefaultText='DefaultText'}"/>
```
As I said TranslateMe lib is obsolete for at least a year now and will not get updates (bug corrections, new functionnalities...).

If you want to keep TranslateMe. Feel free to adapt your own Tr Markup from [Here](https://github.com/codingseb/Localization/blob/master/CodingSeb.Localization.WPF/Tr.cs) (it's MIT licenced) or eventually to make your own MultiBinding->IMultiValueConverter to make it work.
