### ISSUE TITLE
How to update language in real-time without change language in combobox

### ISSUE THREAD

**Issue by linhmc** [codingseb/Localization#2]
Hi @codingseb ,
I am coding to help user can change language in real-time. That mean user change in .tm.json file and save in text editor, in UI when user refresh button it change language automatically
![image](https://user-images.githubusercontent.com/20184892/100715956-90d25780-33ea-11eb-85c4-efccfdc35b05.png)
How can I reach it?

**Comment by linhmc** [comment]
Hi @codingseb 

In Loc.cs class I suggest add method. 

```c#
public void RaiseLanguageChange()
{
    TMLanguageChangingEventArgs changingArgs = new TMLanguageChangingEventArgs(currentLanguage, currentLanguage);
    TMLanguageChangedEventArgs changedArgs = new TMLanguageChangedEventArgs(currentLanguage, currentLanguage);
    CurrentLanguageChanging?.Invoke(this, changingArgs);
    if (!changingArgs.Cancel)
    {
        CurrentLanguageChanged?.Invoke(this, changedArgs);
    }
}
```

![image](https://user-images.githubusercontent.com/20184892/100726204-3be90e00-33f7-11eb-8a6c-69a5b5263c75.png)

Developer can invoke to update language. Please consider.

**Comment by codingseb** [comment]
Hello again @linhmc 
Yes it's a good idea. Thanks for it.

I will include it in [Loc.cs](https://github.com/codingseb/Localization/blob/master/CodingSeb.Localization/Loc.cs) as soon as possible and publish a new CodingSeb.Localization version

**Comment by codingseb** [comment]
Ok I published :  
* [CodingSeb.Localization : 1.1.2.0](https://www.nuget.org/packages/CodingSeb.Localization/1.1.2)
* [CodingSeb.Localization.JsonfileLoader : 1.1.2.0](https://www.nuget.org/packages/CodingSeb.Localization.JsonFileLoader/1.1.2)
* [CodingSeb.Localization.YamlFileLoader : 1.1.2.0](https://www.nuget.org/packages/CodingSeb.Localization.YamlFileLoader/1.1.2)
* [CodingSeb.Localization.WPF : 1.1.5.0](https://www.nuget.org/packages/CodingSeb.Localization.WPF/1.1.5)

To allow hot reloading of files and implement the method `RaiseLanguageChangeEvents` in class `Loc`.
I also implemented an example of hot reloading in [CodingSeb.Localization.Examples](https://github.com/codingseb/Localization/tree/master/CodingSeb.Localization.Examples).
See :
* In [MainWindow.xaml](https://github.com/codingseb/Localization/blob/master/CodingSeb.Localization.Examples/MainWindow.xaml)  
```xml
<Button x:Name="LanguageChangedRefreshButton" 
        DockPanel.Dock="Right"
        Content="Refresh"
        Click="LanguageChangedRefreshButton_Click" />
```
* In [MainWindow.xaml.cs](https://github.com/codingseb/Localization/blob/master/CodingSeb.Localization.Examples/MainWindow.xaml.cs)

```c#
private void LanguageChangedRefreshButton_Click(object sender, RoutedEventArgs e)
{
    Languages.ReloadFiles();
    Loc.Instance.RaiseLanguageChangeEvents();
}
```
* And in [Languages.cs](https://github.com/codingseb/Localization/blob/master/CodingSeb.Localization.Examples/Utils/Languages.cs)

```c#
public static void ReloadFiles()
{
    string exampleFileFileName = Path.Combine(languagesFilesDirectory, "Example1.loc.json");
    LocalizationLoader.Instance.ClearAllTranslations();
    LocalizationLoader.Instance.AddFile(exampleFileFileName);
}
```

**Comment by linhmc** [comment]
Many thanks @codingseb.
