### ISSUE TITLE
Is support JSON Array?

### ISSUE THREAD

**Issue by azhe403** [codingseb/Localization#4]
To avoid write long text single line, is any support JSON array string like this?

```
{
  "SomeString": {
    "id": [
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
      "\nLorem Ipsum has been the industry's standard dummy text ever since the 1500s",
      "\nwhen an unknown printer took a galley of type and scrambled it to make a type specimen book.."
    ],
    "en": [
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. ",
      "\nLorem Ipsum has been the industry's standard dummy text ever since the 1500s",
      "\nwhen an unknown printer took a galley of type and scrambled it to make a type specimen book.."
    ]
  }
}
```

I got this exception
![image](https://user-images.githubusercontent.com/17938038/162082202-6dc4eade-785b-45ff-9034-860456833e5a.png)

**Comment by codingseb** [comment]
Hello @azhe403.
Sorry for  my late answer.
Arrays are not supported by the default CodingSeb.Localization.JsonFileLoader.

But you could implement your own `ILocalizationFileLoader` and make a loader that support it.
You can base it on [JsonFileLoader.cs](https://github.com/codingseb/Localization/blob/master/CodingSeb.Localization.JsonFileLoader/JsonFileLoader.cs)
